<?php

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-login/style.css'
);
$form = $this->form;
$form->prepare();
?>

<div class="error"></div>

<?php
echo $this->form()->openTag($form);
//Helps prevent this form's posts from effecting other plugins
echo $this->formInput($form->get('rcmPluginName'));
?>

<table width="60%">
    <?php if ($this->postSuccess): ?>

        <tr>
            <td>
                <br><br><strong>
                    <?= $this->translate('If you entered valid information and we have an email on file for your account, you will receive an email shortly that you can use to reset your password. Don\'t forget to check your spam folder.') ?>
                </strong>
            </td>
        </tr>

    <?php else: ?>
        <tr>
            <td>
                <div data-richEdit="top">
                    <?= $this->instanceConfig['top'] ?>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <p>&nbsp;</p>
            </td>
        </tr>
        <tr>
            <td height="10px">
                <div class="error">
                    <?= isset($error) ? $this->translate($error) : '' ?>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <p>&nbsp;</p>
            </td>
        </tr>
        <tr>
            <td>
                <?= $this->labelHelper->getHtml($form->get('userId'), $this->instanceConfig); ?>
                <?= $this->formInput($form->get('userId')); ?>
            </td>
        </tr>
        <tr>
            <td>
                <p>&nbsp;</p>
            </td>
        </tr>

        <tr>
            <td>
                <button class="btn btn-primary" type="submit">
                    <?=
                    $this->rcmTextEdit(
                        'button',
                        'Continue',
                        'span'
                    )
                    ?>
                </button>
            </td>
        </tr>

    <?php endif ?>

</table>

<?= $this->form()->closeTag($form); ?>
