<?php

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-create-new-password/style.css'
);
$this->headScript()->appendFile(
    $this->basePath()
    . '/modules/rcm-create-new-password/rcm-create-new-password.js',
    'text/javascript'
);
$form = $this->form;
$form->prepare();
?>
    <script type="text/javascript">
        $(function () {
            new RcmCreateNewPassword(
                <?=  $this->instanceId?>,
                <?=  json_encode($this->instanceConfig['translate'])?>
            );
        });
    </script>

    <div class="error"></div>

<?php
echo $this->form()->openTag($form);
//Helps prevent this form's posts from effecting other plugins
echo $this->formInput($form->get('rcmPluginName'));
?>

    <table style="border:0;" width="310">

        <tr>
            <td colspan="2">
                <div data-richEdit="top">
                    <?= $this->instanceConfig['top'] ?>
                </div>
            </td>
        </tr>


        <?php if ($this->postSuccess): ?>

            <tr>
                <td>
                    <?= $this->instanceConfig['thankYou'] ?>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
            </tr>

        <?php else: ?>
            <tr>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td height="10px" colspan="2">
                    <div class="error">
                        <?= isset($error) ? $error : '' ?>
                    </div>
                </td>
            </tr>
            <?php if($this->hideForm != true):?>
            <tr>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td>
                    <?= $this->rcmLabel($form->get('password')); ?>
                </td>
                <td style="width:33%">
                    <?= $this->formInput($form->get('password')); ?>
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: right">
                    <div data-richEdit="alphanumeric">
                        <?= $this->instanceConfig['alphanumeric'] ?>
                        <p>&nbsp;</p>
                    </div>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <tr>
                <td>
                    <?= $this->rcmLabel($form->get('passwordTwo')); ?>
                </td>
                <td style="width:33%">
                    <?= $this->formInput($form->get('passwordTwo')); ?>
                </td>

            </tr>
            <tr>
                <td>
                    <p>&nbsp;</p>
                </td>
                <td>
                    <p>&nbsp;</p>
                </td>
            </tr>
            <td>
                <p>&nbsp;</p>
            </td>
            <td style="text-align: right">
                <button class="btn btn-primary" type="submit">
                    <span data-textEdit="button"><?= $this->instanceConfig['button'] ?></span>
                </button>
            </td>
            </tr>
            <?php endif ?>
        <?php endif ?>

    </table>

<?= $this->form()->closeTag($form); ?>
